package_name = "ros2_sick"
repo = "https://github.com/iscumd/isc_sick"

[[nodes]]
node_name = 'ros2_sick'
#Relitive to this file
source_file = ['./src/ros2_sick.cpp']
summary = '''
This is a Ros2 Driver for the Sick LMS-111 2D LiDAR.

Currently only supports POSIX operating systems.
'''

potential_improvements = '''Lots and Lots of refactoring'''

[[nodes.publishes]]
name = '/scan'
description = 'laserscans from the LiDAR'

[[nodes.params]]
name = 'host'
description = 'IP of the LiDAR'

[[nodes.params]]
name = 'frame_id'
description = 'Frame the LiDAR publishes to.'

[[nodes.params]]
name = 'port'
description = 'Port the LiDAR is listening on.'

[[nodes.params]]
name = 'tf_correction'
description = 'Corrects scan angle for the tf frame(?)'

[[nodes.launch]]
file_path = './launch/ros2_sick.launch.py'
usage = ''' 
Just launches the node without args.
'''
